### ISSUE TITLE
Bug in heuristic when using "reverse" for route merging

### ISSUE THREAD

**Issue by Jakob-B** [mattianeroni/clarke-wright-savings#3]
When merging routes with a edge which does not start at the last node from the first route or does not end with the same node as the first node from the second route, a reversing option may be used. This reverse option has three different cases:

- Case I: Start of new edge is also start of first route (i) and end of new edge is also end of second route (j). -> reverse the edge
- Case II: Start of new edge is also start of first route (i) and end of new edge is start of second route (j). -> reverse first route
- Case III: Start of new edge is end of first route (i) and end of new edge is end of second route (j). -> reverse second route

In the code covering this part there are two little bugs. 

First of all, the first case reverses the edge `redge`, but this edge is never used. Additionally, this would also require the both routes to "switch places". 

Secondly, the cases are not separated by `if...elfi...elif`, instead using `if...if...if`. It is therefore possible, that more than one case is true and gets executed. 

Some example:

Regarding the first point: routes [(depot-2)(2-1)(1-depot)] and [(depot-4)(4-3)(3-depot)] and new edge  (2-3). Here, case I holds, as the start of the edge is start of first route and end of new edge is end of second route. However, as I said in the first point, only reversing (2-3) would not create a feasible merged route, instead [(depot-2)(2-1)(3-2)(4-3)(3-depot)] is created. (Additionally, the reversed edge is never used in the code).
Instead, both routes should be reversed and not the edge, creating  [(depot-1)(1-2)(2-3)(3-4)(4-depot)].

Regarding the second point: same example as above, but this time the second route only is one node,  [(depot-3)(3-depot)]. Now, case I holds again. But also case II is true, as node 3 is start **and** end of route 2. Remember, the original code in case I has no real effect so far. In case II we reverse the first route and merge, creating [(depot-1)(1-2)(2-3)(3-depot)], an **accidentaly** feasible route. 

Sum up: Fixing the bugs by 1) in Case I, reverse both routes, keep edge unchanged and 2) use `elif` instead of `if`.

I will create a commit and pull request.

Please correct me where I'm wrong. Maybe I missed some trick in the code that actually makes the original version work as intended.

Thanks

Jakob

**Comment by mattianeroni** [comment]
Solved
